# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fight' do
	
  platform :ios, '7.0'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'UnityAds'
  pod 'UMengAnalytics'

end
